In [37]:
import pandas as pd

df = pd.read_excel('Berlin_accidents_clean_2018_2021.xlsx')
df

id  land  district  year  month  hour  day_of_week  \
0      219249    11         3  2021     11    18            2   
1      219248    11         7  2021     12    19            7   
2      219247    11         4  2021     12    17            4   
3      219246    11         4  2021     12    15            7   
4      219243    11        11  2021     12     9            5   
...       ...   ...       ...   ...    ...   ...          ...   
50108  208846    11         4  2018     12    10            6   
50109  208848    11         3  2018     12    10            6   
50110  208850    11         2  2018     12     9            6   
50111  208851    11        11  2018     12     9            6   
50112  208853    11         7  2018     12     7            6   

       accident_category  accident_details  accident_type  light_condition  \
0                      3                 0              3                2   
1                      3                 6              2                2   
2                      3                 5              2                2   
3                      3                 5              2                1   
4                      3                 3              6                0   
...                  ...               ...            ...              ...   
50108                  3                 5              3                0   
50109                  3                 5              7                0   
50110                  3                 2              6                0   
50111                  2                 0              7                1   
50112                  3                 5              3                1   

       acc_with_bike  acc_with_car  acc_with_ped  acc_with_motobike  \
0                  0             1             0                  1   
1                  0             1             1                  0   
2                  0             1             0                  0   
3                  0             1             0                  1   
4                  0             1             0                  0   
...              ...           ...           ...                ...   
50108              0             1             0                  0   
50109              1             1             0                  0   
50110              0             1             0                  0   
50111              1             0             0                  0   
50112              0             1             0                  0   

       acc_with_truck  acc_with_other  road_condition  longitude   latitude  
0                   0               0               1  13.426895  52.533940  
1                   0               0               1  13.392090  52.439951  
2                   0               0               0  13.326242  52.538028  
3                   0               0               1  13.316521  52.499534  
4                   0               1               2  13.525752  52.493867  
...               ...             ...             ...        ...        ...  
50108               0               0               0  13.266868  52.514261  
50109               0               0               1  13.460732  52.563879  
50110               0               0               1  13.451028  52.527412  
50111               0               0               1  13.461215  52.525101  
50112               0               0               1  13.403144  52.463429  

[50113 rows x 20 columns]

In [38]:
#X, y split
y=pd.DataFrame(df['accident_category'])
#X=data_num
X=df[['district','month', 'hour','day_of_week','accident_details', 'accident_type','light_condition','acc_with_bike',
                 'acc_with_car', 'acc_with_ped','acc_with_motobike', 'acc_with_truck','acc_with_other', 'road_condition']].copy()
X

district  month  hour  day_of_week  accident_details  accident_type  \
0             3     11    18            2                 0              3   
1             7     12    19            7                 6              2   
2             4     12    17            4                 5              2   
3             4     12    15            7                 5              2   
4            11     12     9            5                 3              6   
...         ...    ...   ...          ...               ...            ...   
50108         4     12    10            6                 5              3   
50109         3     12    10            6                 5              7   
50110         2     12     9            6                 2              6   
50111        11     12     9            6                 0              7   
50112         7     12     7            6                 5              3   

       light_condition  acc_with_bike  acc_with_car  acc_with_ped  \
0                    2              0             1             0   
1                    2              0             1             1   
2                    2              0             1             0   
3                    1              0             1             0   
4                    0              0             1             0   
...                ...            ...           ...           ...   
50108                0              0             1             0   
50109                0              1             1             0   
50110                0              0             1             0   
50111                1              1             0             0   
50112                1              0             1             0   

       acc_with_motobike  acc_with_truck  acc_with_other  road_condition  
0                      1               0               0               1  
1                      0               0               0               1  
2                      0               0               0               0  
3                      1               0               0               1  
4                      0               0               1               2  
...                  ...             ...             ...             ...  
50108                  0               0               0               0  
50109                  0               0               0               1  
50110                  0               0               0               1  
50111                  0               0               0               1  
50112                  0               0               0               1  

[50113 rows x 14 columns]

In [39]:
# Import the required libraries and modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_boston
from sklearn.datasets import load_iris, load_breast_cancer
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import plot_tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.preprocessing import StandardScaler

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

%matplotlib inline

In [40]:
# Split the data into a training set and a test set.
TT_SPLIT = 0.2     # ratio train/test size #proportion test set split
RAND_STATE = 123   # specifies a sampling for repeatable results
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=TT_SPLIT,random_state=RAND_STATE)

In [41]:
y_test

accident_category
8583                   3
22514                  3
11364                  3
34283                  3
13256                  3
...                  ...
32197                  2
40550                  3
26106                  3
1025                   3
18893                  3

[10023 rows x 1 columns]

In [42]:
df['accident_category'].value_counts() # My dataset is very unbalanced.

3    42409
2     7553
1      151
Name: accident_category, dtype: int64

In [43]:
# Balancing data using SMOTE
# Upsampling
from imblearn.over_sampling import SMOTE
smote = SMOTE()
X_sm, y_sm = smote.fit_resample(X_train, y_train)
y_sm.value_counts()

accident_category
3                    33876
2                    33876
1                    33876
dtype: int64

In [44]:
#RandomUpSampler 
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=42)
X_train_res, y_train_res = ros.fit_resample(X_sm, y_sm)

X_train_res = pd.DataFrame(X_train_res, columns= X_train.columns)
y_train_res = pd.DataFrame(y_train_res, columns =['accident_category'])

In [45]:
y_train_res.value_counts() #now we have a balanced data

accident_category
3                    33876
2                    33876
1                    33876
dtype: int64

In [46]:
#Best parameters from all_years: {'bootstrap': True, 'max_depth': 30, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 150, 'oob_score': False, 'random_state': 123}
#Validation accuracy: 0.8637486098367824

#Trying best parameters from cv

from sklearn.naive_bayes import CategoricalNB
from sklearn.ensemble import RandomForestClassifier

parameters = {"max_depth":30,   #level of decision tree
           "min_samples_leaf":5, 
           "max_features": None, #number of columns
           "n_estimators":150, #number of decision trees
           "bootstrap":True, 
           "oob_score":False,
           "random_state":123}

rf = RandomForestClassifier(**parameters)
rf.fit(X_train_res, y_train_res['accident_category'])


print("train prediction accuracy score: %.2f" %(rf.score(X_train_res, y_train_res)))
print("test prediction accuracy score: %.2f"  %(rf.score(X_test, y_test)))

train prediction accuracy score: 0.93
test prediction accuracy score: 0.72


In [47]:
#Best parameters from 2021: {'bootstrap': False, 'max_depth': 30, 'max_features': 'sqrt', 'min_samples_leaf': 5, 'n_estimators': 150, 'oob_score': False, 'random_state': 123}
#Validation accuracy: 0.8796706557042387

#Trying best parameters from cv

from sklearn.naive_bayes import CategoricalNB
from sklearn.ensemble import RandomForestClassifier

parameters = {"max_depth":30,   #level of decision tree
           "min_samples_leaf":8, 
           "max_features": "sqrt", #number of columns
           "n_estimators":150, #number of decision trees
           "bootstrap":False, 
           "oob_score":False,
           "random_state":123}

rf = RandomForestClassifier(**parameters)
rf.fit(X_train_res, y_train_res['accident_category'])


print("train prediction accuracy score: %.2f" %(rf.score(X_train_res, y_train_res)))
print("test prediction accuracy score: %.2f"  %(rf.score(X_test, y_test)))

train prediction accuracy score: 0.89
test prediction accuracy score: 0.73


In [48]:
#Cross validation

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import CategoricalNB



parameters = {
    "max_depth": [10, 20, 30],   #level of decision tree
    "min_samples_leaf": [5, 8, 10],
    "max_features": [None, "sqrt", "log2"], #number of columns
    "n_estimators": [50, 100, 150], #number of decision trees
    "bootstrap": [True, False], 
    "oob_score": [False],
    "random_state": [RAND_STATE]
}

rf = RandomForestClassifier()

grid_search = GridSearchCV(rf, parameters, cv=5)
grid_search.fit(X_train_res, y_train_res['accident_category'])

print("Best parameters:", grid_search.best_params_)
print("Validation accuracy:", grid_search.best_score_)


Best parameters: {'bootstrap': False, 'max_depth': 30, 'max_features': 'sqrt', 'min_samples_leaf': 5, 'n_estimators': 150, 'oob_score': False, 'random_state': 123}
Validation accuracy: 0.8626859794210459


Best parameters: {'bootstrap': False, 'max_depth': 30, 'max_features': 'sqrt', 'min_samples_leaf': 5, 'n_estimators': 150, 'oob_score': False, 'random_state': 123}
Validation accuracy: 0.8626859794210459